<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net481</TargetFrameworks>
		<RootNamespace>Genetec.Dap.CodeSamples</RootNamespace>
		<AssemblyName>AudioRecorderSample</AssemblyName>
		<Description>Sample project</Description>
		<Copyright>Copyright © Genetec Inc. 2025</Copyright>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
		<PlatformTarget>AnyCPU</PlatformTarget>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
		<PlatformTarget>AnyCPU</PlatformTarget>
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net481'">
		<Reference Include="Genetec.Sdk">
			<HintPath>$(GSC_SDK)\Genetec.Sdk.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Genetec.Sdk.Media">
			<HintPath>$(GSC_SDK)\Genetec.Sdk.Media.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="System" />
		<Reference Include="System.Core" />
	</ItemGroup>


	<Import Project="..\..\Shared\Shared.projitems" Label="Shared" />

</Project>